        ### .   - Add User ssh keys to remote systems

- hosts: all
  become: yes
  become_method: sudo
  connection: ssh      
  tasks:
    - name: Add User with ssh-key
      user:
        name: bob
        comment: "this user has ssh"
        shell: /bin/csh
        generate_ssh_key: yes
        state: present
        
